<?php


namespace App\Helpers\Constants;

class EbayCsvHeader
{
    const EBAY_CSV_HEADER = [
        "SKU",
        "Localized For",
        "Variation Group ID",
        "Variation Specific Name 1",
        "Variation Specific Value 1",
        "Variation Specific Name 2",
        "Variation Specific Value 2",
        "Variation Specific Name 3",
        "Variation Specific Value 3",
        "Variation Specific Name 4",
        "Variation Specific Value 4",
        "Variation Specific Name 5",
        "Variation Specific Value 5",
        "Title",
        "Subtitle",
        "Product Description",
        "Additional Info",
        "Group Picture URL",
        "Picture URL 1",
        "Picture URL 2",
        "Picture URL 3",
        "Picture URL 4",
        "Picture URL 5",
        "Picture URL 6",
        "Picture URL 7",
        "Picture URL 8",
        "Picture URL 9",
        "Picture URL 10",
        "Picture URL 11",
        "Picture URL 12",
        "UPC",
        "ISBN",
        "EAN",
        "MPN",
        "Brand",
        "ePID",
        "Attribute Name 1",
        "Attribute Value 1",
        "Attribute Name 2",
        "Attribute Value 2",
        "Attribute Name 3",
        "Attribute Value 3",
        "Attribute Name 4",
        "Attribute Value 4",
        "Attribute Name 5",
        "Attribute Value 5",
        "Attribute Name 6",
        "Attribute Value 6",
        "Attribute Name 7",
        "Attribute Value 7",
        "Attribute Name 8",
        "Attribute Value 8",
        "Attribute Name 9",
        "Attribute Value 9",
        "Attribute Name 10",
        "Attribute Value 10",
        "Attribute Name 11",
        "Attribute Value 11",
        "Attribute Name 12",
        "Attribute Value 12",
        "Attribute Name 13",
        "Attribute Value 13",
        "Attribute Name 14",
        "Attribute Value 14",
        "Attribute Name 15",
        "Attribute Value 15",
        "Attribute Name 16",
        "Attribute Value 16",
        "Attribute Name 17",
        "Attribute Value 17",
        "Attribute Name 18",
        "Attribute Value 18",
        "Attribute Name 19",
        "Attribute Value 19",
        "Attribute Name 20",
        "Attribute Value 20",
        "Attribute Name 21",
        "Attribute Value 21",
        "Attribute Name 22",
        "Attribute Value 22",
        "Attribute Name 23",
        "Attribute Value 23",
        "Attribute Name 24",
        "Attribute Value 24",
        "Attribute Name 25",
        "Attribute Value 25",
        "Attribute Name 26",
        "Attribute Value 26",
        "Attribute Name 27",
        "Attribute Value 27",
        "Attribute Name 28",
        "Attribute Value 28",
        "Attribute Name 29",
        "Attribute Value 29",
        "Attribute Name 30",
        "Attribute Value 30",
        "Attribute Name 31",
        "Attribute Value 31",
        "Attribute Name 32",
        "Attribute Value 32",
        "Attribute Name 33",
        "Attribute Value 33",
        "Attribute Name 34",
        "Attribute Value 34",
        "Attribute Name 35",
        "Attribute Value 35",
        "Attribute Name 36",
        "Attribute Value 36",
        "Attribute Name 37",
        "Attribute Value 37",
        "Attribute Name 38",
        "Attribute Value 38",
        "Attribute Name 39",
        "Attribute Value 39",
        "Attribute Name 40",
        "Attribute Value 40",
        "Attribute Name 41",
        "Attribute Value 41",
        "Attribute Name 42",
        "Attribute Value 42",
        "Attribute Name 43",
        "Attribute Value 43",
        "Attribute Name 44",
        "Attribute Value 44",
        "Attribute Name 45",
        "Attribute Value 45",
        "Condition",
        "Condition Description",
        "Measurement System",
        "Length",
        "Width",
        "Height",
        "Weight Major",
        "Weight Minor",
        "Package Type",
        "Total Ship To Home Quantity",
        "Channel ID",
        "Category",
        "Secondary Category",
        "Shipping Policy",
        "Payment Policy",
        "Return Policy",
        "Best Offer Enabled",
        "BO Auto Accept Price",
        "BO Auto Decline Price",
        "List Price",
        "Max Quantity Per Buyer",
        "Strikethrough Price",
        "Minimum Advertised Price",
        "Minimum Advertised Price Handling",
        "Store Category Name 1",
        "Store Category Name 2",
        "Sold Off Ebay",
        "Sold On Ebay",
        "Apply Tax",
        "Tax Category",
        "VAT Percent",
        "Include eBay Product Details",
        "Domestic Shipping P1 Cost",
        "Domestic Shipping P1 Additional Cost",
        "Domestic Shipping P1 Surcharge",
        "Domestic Shipping P2 Cost",
        "Domestic Shipping P2 Additional Cost",
        "Domestic Shipping P2 Surcharge",
        "Domestic Shipping P3 Cost",
        "Domestic Shipping P3 Additional Cost",
        "Domestic Shipping P3 Surcharge",
        "Domestic Shipping P4 Cost",
        "Domestic Shipping P4 Additional Cost",
        "Domestic Shipping P4 Surcharge",
        "International Shipping P1 Cost",
        "International Shipping P1 Additional Cost",
        "International Shipping P1 Surcharge",
        "International Shipping P2 Cost",
        "International Shipping P2 Additional Cost",
        "International Shipping P2 Surcharge",
        "International Shipping P3 Cost",
        "International Shipping P3 Additional Cost",
        "International Shipping P3 Surcharge",
        "International Shipping P4 Cost",
        "International Shipping P4 Additional Cost",
        "International Shipping P4 Surcharge",
        "International Shipping P5 Cost",
        "International Shipping P5 Additional Cost",
        "International Shipping P5 Surcharge",
        "TemplateName",
        "CustomFields",
        "Eligible For EbayPlus",
        "Pictures Vary On",
        "Warehouse Location ID",
        "Hide Buyer Details",
        "Compliance policies",
        "Take-back policy",
        "producerProductId",
        "productPackageId",
        "shipmentPackageId",
        "productDocumentationId",
        "ecoParticipationFee",
        "Hazmat Pictograms",
        "Hazmat SignalWord",
        "Hazmat Statements",
        "Hazmat Component",
        "EnergyEfficiencyLabel ImageURL",
        "EnergyEfficiencyLabel ImageDescription",
        "EnergyEfficiencyLabel ProductInformationSheet",
        "Regional ProductCompliancePolicies",
        "Regional TakeBackPolicies",
        "Condition Descriptor Name 1",
        "Condition Descriptor Value 1",
        "Condition Descriptor Additional Info 1",
        "Condition Descriptor Name 2",
        "Condition Descriptor Value 2",
        "Condition Descriptor Additional Info 2",
        "Condition Descriptor Name 3",
        "Condition Descriptor Value 3",
        "Condition Descriptor Additional Info 3",
        "Condition Descriptor Name 4",
        "Condition Descriptor Value 4",
        "Condition Descriptor Additional Info 4",
    ];
}
